<?php


namespace Tests;


use Illuminate\Foundation\Testing\RefreshDatabase;

class ApiTesting extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->refreshDatabase();
    }

}
