<?php

namespace Tests\Feature;

use App\Car;
use App\User;
use CarsEndpointTest;
use Tests\ApiTesting;

class CarTest extends ApiTesting
{

    private $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed');
        $this->user = User::first();
    }

    /**
     * @test
     */
    public function it_return_cars()
    {
        $response = $this->actingAs($this->user, 'api')->getJson('api/cars');

        $response->assertStatus(200);
    }

    /**
     * @test
     */
    public function it_return_car_by_id()
    {
        $carId = Car::all()->random()->id;
        $response = $this->actingAs($this->user, 'api')->getJson("api/cars/$carId");

        $response->assertStatus(200);
    }

    /**
     * @test
     */
    public function it_delete_car_by_id()
    {
        $carId = Car::all()->random()->id;
        $response = $this->actingAs($this->user, 'api')->call('delete', "api/cars/$carId");

        $response->assertStatus(204);
    }

    /**
     * @test
     */
    public function it_create_car()
    {
        $carTotal = Car::all()->count();

        $response = $this->actingAs($this->user, 'api')
            ->post("api/cars", ['user_id' => $this->user->id, 'make' => 'test', 'model' => 'test model', 'year' => 2012]);

        $response->assertStatus(201);

        $this->assertEquals($carTotal + 1, Car::all()->count());
    }
}
